name: Registry Login
description: Login to Registry for building bundles in CI jobs

inputs:
  username:
    description: Registry1 user
    required: true
  password:
    description: Registry1 PW
    required: true
  download-init-package: 
    description: Include Zarf init package
    required: false
  working-dir:
    description: Zarf package path
    required: true

runs:
  using: composite
  steps:
    - name: Login to Registry1
      uses: docker/login-action@v3
      with:
        registry: registry1.dso.mil
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        
    - name: Install Zarf
      uses: defenseunicorns/setup-zarf@main
      with:
        # renovate: datasource=github-tags depName=defenseunicorns/zarf versioning=semver
        version: v0.29.2
        download-init-package: ${{ inputs.download-init-package }}
        
    - name: Create Zarf Package
      shell: bash
      run: zarf package create --confirm --output ../build
      working-directory: ${{ inputs.working-dir }}